version: "3"
services:
  nodejs:
    image: node
    ports:
      - "4000:4000"
    working_dir: /var/www/html/node
    volumes:
      - ./backend/:/var/www/html/node
    command: node /var/www/html/node/src

  react:
    image: node:alpine
    working_dir: /~/react
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/~/react
    command: npm start

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-73-90-195.eu-west-1.compute.amazonaws.com
            database: dakok3ho0e05he
            schema: public
            user: shlzdwxuriajaf
            password: 055aa8b3d65efebd3f57bbf769864e525583e57160448bd934f33a4b53cf278b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
